FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.15.1 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/application/package.json packages/application/package.json

RUN pnpm install --frozen-lockfile

CMD ["pnpm", "dev:local"]
